export const products = [
  {
    id: 'form-shirt',
    name: 'The Form Shirt',
    category: 'Women',
    type: 'Shirts',
    price: 128,
    color: 'Optic white',
    image: 'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?auto=format&fit=crop&w=900&q=85',
    alt: 'White sculptural shirt styled for an editorial portrait',
    tag: 'BESTSELLER',
  },
  {
    id: 'day-trouser',
    name: 'Day Trouser',
    category: 'Women',
    type: 'Trousers',
    price: 198,
    color: 'Soft graphite',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85',
    alt: 'Tailored dark trousers with a relaxed silhouette',
    tag: 'NEW ARRIVAL',
  },
  {
    id: 'everyday-tee',
    name: 'Everyday Tee',
    category: 'Men',
    type: 'T-shirts',
    price: 48,
    color: 'Washed white',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85',
    alt: 'Essential white cotton t-shirt',
    tag: 'EVERYDAY ICON',
  },
  {
    id: 'everyday-knit',
    name: 'Everyday Knit',
    category: 'Men',
    type: 'Knitwear',
    price: 165,
    color: 'Moss melange',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=85',
    alt: 'Soft green knitwear with a refined everyday fit',
    tag: 'LOW IMPACT',
  },
  {
    id: 'studio-tee',
    name: 'Studio Tee',
    category: 'Women',
    type: 'T-shirts',
    price: 58,
    color: 'Soft black',
    image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=85',
    alt: 'Relaxed black t-shirt styled for the city',
    tag: 'NEW COLOR',
  },
  {
    id: 'straight-denim',
    name: 'Straight Denim',
    category: 'Men',
    type: 'Jeans',
    price: 118,
    color: 'Vintage blue',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85',
    alt: 'Classic straight-leg blue denim jeans',
    tag: 'BESTSELLER',
  },
  {
    id: 'utility-cargo',
    name: 'Utility Cargo',
    category: 'Men',
    type: 'Cargo pants',
    price: 138,
    color: 'Field olive',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85',
    alt: 'Relaxed utility trousers in olive green',
    tag: 'EASY FIT',
  },
  {
    id: 'weekend-polo',
    name: 'Weekend Polo',
    category: 'Men',
    type: 'Polos',
    price: 88,
    color: 'Deep navy',
    image: 'https://images.unsplash.com/photo-1622445275463-afa2ab738c34?auto=format&fit=crop&w=900&q=85',
    alt: 'Navy short-sleeve polo shirt in soft cotton',
    tag: 'NEW ARRIVAL',
  },
  {
    id: 'field-jacket',
    name: 'Field Jacket',
    category: 'Women',
    type: 'Outerwear',
    price: 228,
    color: 'Warm stone',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85',
    alt: 'Structured everyday jacket in a warm neutral tone',
    tag: 'JUST IN',
  },
]

export const collections = ['All pieces', 'Women', 'Men']